version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.5
      - image: circleci/mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: studentoa
            MYSQL_USER: user
            MYSQL_PASSWORD: passw0rd

    working_directory: ~/APIManager/
    steps:
      - run:
          name: Upgrade the system
          command: |
            sudo apt update
            sudo apt install mysql-client
      - run:
          name: Install PHP driver
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-enable pdo_mysql
      - checkout
      - run:
          name: Install phpunit
          command: |
            wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
            chmod +x phpunit
            ./phpunit --version
      - run:      
          name: Waiting for MySQL
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo MySQL is ready! && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Test APIManager.test.php
          command: ./phpunit test/APIManagerTest.php
